### ISSUE TITLE
Better config for years

### ISSUE THREAD

**Issue by AAS97** [rehookify/datepicker#11]
**Context**
I personally find for most of my use-cases that year configuration is not the most practical. In a majority of cases I would like to set asymmetrical min and max years either part of today's date (for example 1900 to 2023). I think this is currently not possible.

**Suggestion**
I would change the `YearsConfig` to something more flexible.
```
type YearsMode = 'decade' | 'fluid';

interface YearsConfig {
  mode: YearsMode,
  minYear : number,
  maxYear : number,
  step: number;
},
```
To prevent breaking changes, both configuration could be handled simultaneously with something like :

```
type YearsMode = 'decade' | 'fluid';

type NumberOfYearConfig =
    | { minYear: number; maxYear: number }
    | { numberOfYears: number };

type YearsConfig = NumberOfYearConfig & {
    mode: YearsMode;
    step: number;
};
```

This will require a change in [create-years.ts](https://github.com/rehookify/datepicker/blob/main/src/utils/create-years.ts) and possibly elsewhere in the codebase

**Comment by Feshchenko** [comment]
@AAS97, hi.
Thanks for reaching out with this question.
Min and max dates do exactly what you needed.
```ts
dates: {
  minDate: new Date(1900, 0, 1),
  maxDate: new Date(2023, 11, 31),
}
```
👆 with this configuration all years, months and days, before minDate and after the maxDate will be disabled.
LMK if this, doesn't help to solve your problem

**Comment by AAS97** [comment]
@Feshchenko, thanks for the prompt answer. The solution works but, `years` is still populated with much more years than I need (and I need to filter them down on `disabled`), and I need to fill `numberOfYears` with a value twice as big as the span I want to display.

**Comment by Feshchenko** [comment]
Do you need a way to generate the exact amount of years with the end of the range bp current year or `maxDate` year?
```ts
dates: {
  maxDate: new Date(2022, 0, 1),
},
yearns: {
  numberOfYears: 100,
}
```
Should produce an array of 100 years from 1923 - 2020.

**Comment by AAS97** [comment]
> ```ts
> dates: {
>   maxDate: new Date(2020, 0, 1),
> },
> yearns: {
>   numberOfYears: 100,
> }
> ```

This does not work as expected. I get 100 years from 2019 to 2118.

**Comment by Feshchenko** [comment]
Yea, I know that it not working as you describe.
I'm asking questions to clarify your need and that I get it right :)

**Comment by AAS97** [comment]
Looks promising ! Well done in such a short time. When do you expect to release ?

**Comment by Feshchenko** [comment]
@AAS97 please try 'exact' mode in [v4.2.0](https://github.com/rehookify/datepicker/releases/tag/v4.2.0)
I hope it will help you
