### ISSUE TITLE
Select same date in range date picker

### ISSUE THREAD

**Issue by gonzarascon** [rehookify/datepicker#18]
Hi! 

First of all, love this library, it has a wonderful and simplistic API!
I was looking for a way to handle the state where a range picker's start/end date is the same. I think this was an edge case that the `range` mode does not contemplate yet. 

For example, [MUI's DateRangePicker](https://mui.com/x/react-date-pickers/date-range-picker/#api) has this option:
![image](https://user-images.githubusercontent.com/35515401/228082833-f2ec2e70-6aa8-4193-a779-f73499a12eb6.png)

It would be great to have a way to enable this feature in the `range` date pickers!

**Comment by kaurkaelep** [comment]
Not sure, but I think its possible by reading the code (haven't tried it myself).

https://github.com/rehookify/datepicker/blob/d8fb696a56c3b1786397482a9b08dd731817db73/src/use-days.ts#L46

use **selectSameDate: true** on the **dates** object

**Comment by Feshchenko** [comment]
Update README in the [v4.3.2](https://github.com/rehookify/datepicker/releases/tag/v4.3.2) release
