### ISSUE TITLE
useDatePicker hook is not refreshing

### ISSUE THREAD

**Issue by Veronika11111** [rehookify/datepicker#19]
Hello,
I really like using your library, but I run into one problem while using it. The hook useDatePicker does not refresh the return values after its arguments are changed. I have sandbox with example - [sandbox here](https://codesandbox.io/s/rehookify-f8j3ww?file=/src/App.tsx).

### Problem 1
The locale of calendar does not change after locale prop is changed - you can try it by clicking on the buttons, the expected behavior is that the calendar locale changes in real time. 

However, when the locale is set at the beginning (try to change the default value of locale in the code) it works perfectly.

### Problem 2
The `data.calendars[0]` does not change after the selected date is changed from the outside of the calendar. 

Expected behaviour -` data.calendars[0]` always contains data about actual month of the selected date, so it changes with selected day change. In my case - the february 2002 is rendered after clicking the `set selected date to 2022-02-02`

Again, when the selected date is set before rendering calendar or by calendar itself, everything works fine. 

I think that both these problems are caused by the fact that useDatePicker is not refreshing after its args are changed. But maybe I am only missing something. 

Thanks.

**Comment by Feshchenko** [comment]
@Veronika11111 , hi, thanks for the feedback and issue 🤗
Problem 1 is clear, I will think about how to handle this (now it is locked inside the internal context).
Problem 2 is much more difficult.
What if the dates mode is `multiple` and you set multiple dates to the `selectedDates`, where to jump?)

**Comment by nutenie-oblacno0a** [comment]
Hello,

### Same problem

I have the same use case as @Veronika11111. Now the library exposes:

```tsx
  const { setYear } = useContextYearsActions();
  const { setMonth } = useContextMonthsActions();
```

and when the input contains valid date, the value of selectedDates changes, and the effect sets the internal calendar to the value.

```tsx
  /**
   * Get day, month and year of first visible item from same month from calendar
   * @param c calendar
   * @returns [day, month, year]
   */
  const getFirstDateFromCalendar = (c: Calendar) => {
    const firstCurrent = c.days.find((d) => d.inCurrentMonth)?.$date;

    if (!firstCurrent) {
      return [];
    }

    const d = firstCurrent.getDay();
    const m = firstCurrent.getMonth();
    const y = firstCurrent.getFullYear();

    return [d, m, y];
  };

  /**
   * Set newDate visible year and month in calendar if not visible
   * @param calendars current calendars (for range are 2)
   * @param newDate new date to handle
   */
  const handleVisibility = (calendars: Calendar[], newDate: Date) => {
    const [, lm, ly] = getFirstDateFromCalendar(calendars[0]);
    const [, rm, ry] = getFirstDateFromCalendar(calendars[1]);

    const cy = newDate.getFullYear();
    const cm = newDate.getMonth();

    if (!(cy !== ly && cm !== lm) && !(cy === ry && cm === rm)) {
      setMonth(newDate);
      setYear(newDate);
    }
  };

  // Listen for change from parent state to start date
  React.useEffect(() => {
    const nextDate = value?.[0];

    if (nextDate) {
      handleVisibility(calendars, nextDate);
    }
  }, [value?.[0]?.toISOString()]);

  // Listen for change from parent state to end date
  React.useEffect(() => {
    const nextDate = value?.[1];

    if (nextDate) {
      handleVisibility(calendars, nextDate);
    }
  }, [value?.[1]?.toISOString()]);
  ```
This is small snipper for RangePicker, but the principle works with single picker too,

@Feshchenko  Can you perhapse expose useContextDaysActions, or some global hook/action to set the current value? 

> What if the dates mode is multiple and you set multiple dates to the selectedDates, where to jump?)
- the easiest option will be _**nothing**_, or listen for focusDate change to determine the jump the developer intended to do. 
- If I change `endDate`, than I set the focusDate to `selectedDates[1]` and the library automaticly shifts the view.

### Same problem different use-case time-picker.

I wanted to use TimePicker as standalone component, but `DatePickerStateProvider` and `useTime` does't listen for changes in `config.time.minTime` or `config.time.maxTime`, so I hahe to unmount the provider when I want to change constrains from outside, or somewhere else is the `focusDate/selectedDays` changed.

**Comment by Feshchenko** [comment]
@Veronika11111 and @nutenie-oblacno0a hi.
Thanks for waiting so long.
I fixed the **First problem** of this issue in [v5.2.0](https://github.com/rehookify/datepicker/releases/tag/v5.2.0)
After updating to the v5.2.0 the sandbox from the first post should work and change locales correctly.
I'm still thinking about the **Second problem**.
In my mind is to allow the user to manipulate `offsetDate` to jump to the needed place.
I will notice here if I have news

**Comment by Feshchenko** [comment]
@Veronika11111 and @nutenie-oblacno0a 
Now you can change `offsetDate` by passing it into config and using new `useDatePickerOffsetPropGetters` hook

**Comment by Feshchenko** [comment]
@Veronika11111 and @nutenie-oblacno0a 
In the v6 you can manipulate offsetDate outside of hooks with
```
const [offsetDate, onOffsetChange] = useState<Date>(new Date());
```
and passing them to config.
Also you can use new `useDatePickerOffsetPropGetters` hook 
I consider this issue as closed, please LMK if this will not help you
