### ISSUE TITLE
Key values are invalid in example

### ISSUE THREAD

**Issue by gruschis** [rehookify/datepicker#26]
Hey 👋 

I was just tinkering around with your library. Thank you for starting such a project!

In your Quickstart hooks example, the keys are invalid since some of them are duplicated. 

```javascript
// example in the README
{days.map((dpDay) => (
  <li key={`${month}-${dpDay.day}`}>
    <button {...dayButton(dpDay, { onClick: onDayClick })}>
      {dpDay.day}
    </button>
  </li>
))}
```

You're interpolating the current month and the day value, so there will be duplicates with the days from the previous and the next month. I'd just print the date string representation of the `$date` property.
```javascript
{days.map((dpDay) => (
  <li key={dpDay.$date.toDateString()}>
    <button {...dayButton(dpDay, { onClick: onDayClick })}>
      {dpDay.day}
    </button>
  </li>
))}
```

**Comment by Feshchenko** [comment]
@gruschis, hello again.
I was waiting to your contribution, but made everything by myself :)
The docs was changed in v5.2.1

**Comment by Feshchenko** [comment]
@gruschis, hello again.
I was waiting to your contribution, but made everything by myself :)
The docs was changed in v5.2.1

**Comment by gruschis** [comment]
@Feshchenko Thank you! Next time, I'll see something, I'll create a PR right away.
