### ISSUE TITLE
Features Missing according to documentation. Please update documentation and examples. 

### ISSUE THREAD

**Issue by Reddemonfox** [rehookify/datepicker#33]
Features Missing according to documentation. Please update documentation and examples

**Comment by Feshchenko** [comment]
@Reddemonfox , hey.
Can you name features what are missing in the docs?

**Comment by Feshchenko** [comment]
@Reddemonfox the doc was updated please check [v6.0.1](https://github.com/rehookify/datepicker/releases/tag/v6.0.1)
