### ISSUE TITLE
 nextMonthButton and previousMonthButton are missing from prop getters

### ISSUE THREAD

**Issue by YoavGrosman** [rehookify/datepicker#34]

**Comment by Feshchenko** [comment]
@YoavGrosman, thanks for submitting this issue.
They were removed in [v6.0.0](https://github.com/rehookify/datepicker/releases/tag/v6.0.0).
I will update doc today

**Comment by Feshchenko** [comment]
Updated the [doc](https://github.com/rehookify/datepicker/releases/tag/v6.0.1)
