### ISSUE TITLE
Start of Years

### ISSUE THREAD

**Issue by asharonbaltazar** [rehookify/datepicker#35]
Hello, and kudos to you for such a wonderful library 🚀. 

I'm building a year dropdown that allows users to select a year. However, it only goes back to 2019. I'd like it to go back further than that. I know I can specify a number of years in the `years` property in `useDatePicker`, but that only works for the future. Any way to set a start year or something similar? Maybe it's adjusting the offset – I'm not sure how it works. 

Thank you!

**Comment by Feshchenko** [comment]
@asharonbaltazar, hey.
Not sure I got you.
Do you have a problem with next/previous years buttons?
Do you want to see more years on one page?

You can change the number of displayed years and mode, check in the [Years Configuration doc](https://github.com/rehookify/datepicker#years-configuration).
```
    years: {
      numberOfYears: 30,
      mode: 'fluid'
    }
```

**Comment by asharonbaltazar** [comment]
Thanks for replying. I'm mapping the `years` array, which is found as a property in the `data` object returned by `useDatePicker`. The earliest year in the list is 2019. I'd like it to go further back. 

Does that make sense?

**Comment by asharonbaltazar** [comment]
Ah, so if I understand correctly, I have to programmatically go back using `previousYearsButton`.

**Comment by Feshchenko** [comment]
Years have pagination. Number of years on one page defined by `numberOfYears` in the  [Years Configuration](https://github.com/rehookify/datepicker#years-configuration).
And you can change mode, for example, `fluid` will put a cursor in the middle.
 If you want to go back, you have 2 options:
- increase `numberOfYears` 
- use `previousYearsButton` and `nextYearsButton` to change the page

**Comment by Feshchenko** [comment]
@asharonbaltazar , and you can check [**examples**](https://github.com/rehookify/datepicker/blob/main/EXAMPLES.md)
You can fork and play with them
