### ISSUE TITLE
How to change years independently for only one calendar

### ISSUE THREAD

**Issue by kangah-codes** [rehookify/datepicker#37]
I've added a dropdown feature to my date range picker, allowing users to pick a specific year for filtering purposes. This way, users can easily select past dates they want to filter, like choosing 1st Feb 2022 - 1st Feb 2023, without manually scrolling through months. However, I've hit a snag. Changing the year in one calendar affects all the calendars in the date range. As a result, users can't easily select dates from different years.

Here's a visual of what I mean:

![Untitled design (2)](https://github.com/rehookify/datepicker/assets/47978604/70ca0547-d223-4f2f-8cb6-d1ece730e16c)
This is an example of how it looks.

The date selection functionality still works, but users need to reselect the current year on the second calendar. I've gone through the documentation, but I couldn't find any hooks or methods to maintain separate states for the two calendars. Any ideas on how to work around this would be greatly appreciated. Thank you!

**Comment by Feshchenko** [comment]
@kangah-codes, hey
I believe that this is something similar to the request from this issue https://github.com/rehookify/datepicker/issues/13
It is not implemented but you can check the code example there
