### ISSUE TITLE
Problem with maxDate and month view

### ISSUE THREAD

**Issue by fweinaug** [rehookify/datepicker#38]
When I set a maxDate and try to navigate to the month of the maxDate in the month view the button to go to next date gets disabled on the month before. In the year view the month is enabled and after clicking on it, the navigation in the month view works as expected.

I created an example here: https://codesandbox.io/p/sandbox/rehookify-all-in-one-month-calendar-forked-cdppw3?file=/src/app.tsx:37,37

Version: 6.1

**Comment by Feshchenko** [comment]
@fweinaug hey, thanks for the issue.
Sorry for the long response and fix. It should be fine in the 6.2.0

**Comment by alizadeh118** [comment]
Hey @Feshchenko,

It appears the problem still exists in version 6.2.0 but not in [this example](https://codesandbox.io/p/sandbox/rehookify-all-in-one-month-calendar-176kep) (version 6.0.1).

Here is [the link to the sandbox](https://codesandbox.io/p/sandbox/rehookify-maxdate-problem-2z269v?file=%2Fsrc%2Fapp.tsx%3A36%2C37).

Thank you in advance.

![maxDate-issue](https://github.com/rehookify/datepicker/assets/131462844/3223d9f5-37ab-4b1d-85c6-0b0c9bed0e02)
