### ISSUE TITLE
Set Option to Modify Start of Weekday

### ISSUE THREAD

**Issue by kecoliva** [rehookify/datepicker#5]
The library starts the weekday only on Monday. It would be great to allow it to start on Sunday.

**Comment by Feshchenko** [comment]
Hi, thanks for the proposition.
I will add it to the backlog.

**Comment by Feshchenko** [comment]
Hey @kecoliva!

I wanted to let you know that I've just added this feature to our date picker. You can now customize the starting day of the week for the calendar. Please check the release note for more information https://github.com/rehookify/datepicker/releases/tag/v3.1.0

Let me know if you have and feedback or questions.

**Comment by kecoliva** [comment]
Thank you so much, @Feshchenko! Really awesome work you have here. Hope this gets the recognition it deserves! Sharing the the calendar I built using this. 🤘🏻

![image](https://user-images.githubusercontent.com/46006869/213922777-38cb6564-7ad2-4123-a544-b03e6fdcf08d.png)
