### ISSUE TITLE
Selecting time with set_focus_date

### ISSUE THREAD

**Issue by armanpwnz** [rehookify/datepicker#52]
Hi,

I select the date and time, then hide <DateProvider> with the button, and then when I open it I can't select the time without the code like this: 

`  useEffect(() => {
    dispatch({ type: "SET_FOCUS_DATE", date: selectedDates[0] });
  }, [dispatch, selectedDates]);`

https://codesandbox.io/p/devbox/time-selection-useeffect-wpz4dr?file=%2Fsrc%2Fcomponents%2Ftime.tsx here a example with a toggle button

Thanks

**Comment by Feshchenko** [comment]
Hey, @armanpwnz your link is not working

**Comment by Feshchenko** [comment]
<img width="1728" alt="Знімок екрана 2024-03-28 о 21 17 14" src="https://github.com/rehookify/datepicker/assets/7198398/743d8d86-1d22-426d-bb39-2487d9794068">
still not working 🤷

**Comment by armanpwnz** [comment]
@Feshchenko   https://codesandbox.io/p/devbox/time-selection-useeffect-wpz4dr?file=%2Fsrc%2Fcomponents%2Ftime.tsx should work, ыorry, I forgot to access the sandbox.

**Comment by Feshchenko** [comment]
Hey @armanpwnz, I hope you are doing well.
What is happening in your example, the **focusDate** is the internal datepicker state. So when you hide and show it the state is lost, that's how React works.
You have a [focusDate](https://www.rehookify.com/datepicker/configuration#general-configuration) prop in configuration.
So what you need to do is to persist it outside of UI that will be hidden.
Here is a link to [Sanbox](https://codesandbox.io/p/sandbox/time-picker-with-toggle-button-jsx33c) with a working example without `useEffect` and manual dispatch, (but your solution is also good)
