### ISSUE TITLE
Give an option to set start date as empty as well

### ISSUE THREAD

**Issue by ayushcs** [rehookify/datepicker#56]
We should have option so that we can set start date as null/empty as well and pass only end date as first like:

onDatesChange([null, new Date()]) // gives error now

to set both date empty we use 

onDatesChange([])

@Feshchenko

**Comment by Feshchenko** [comment]
@ayushcs hey, thanks for reaching.
Please provide more context and use case.

**Comment by Feshchenko** [comment]
Explained in https://github.com/rehookify/datepicker/pull/48
