### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by nick-tw** [rehookify/datepicker#58]
https://www.rehookify.com/datepicker/locale-configuration

"[hour, monute, second and hour12](https://www.rehookify.com/datepicker/locale-configuration#hour-monute-second-and-hour12)"

Should be minute

And [Locale configuration](https://www.rehookify.com/date-picker/locale-configuration)

Links to "/date-picker" in url. should be "/datepicker"

**Comment by Feshchenko** [comment]
Hey, @nick-tw, thanks for reaching.
All issues should be addressed, please check if you have a time.
