### ISSUE TITLE
How do I change the time?

### ISSUE THREAD

**Issue by resting** [rehookify/datepicker#59]
Logging the date value after clicking the date, it's -8hrs from the selected date.

Example: 
logged: [2024-05-03T16:00:00.000Z]
expected: [2024-05-04T00:00:00.000Z]

Do I have to supply an offset? Could you provide some examples of how to do that?

Based on single date selection. No time selection is available.

Thanks.

**Comment by Feshchenko** [comment]
Hey, @resting, it looks like you are using `toISOString()` on selected dates.
This is the default browser behaviour.

```
const d = new Date(2024, 7, 9)
console.log(d) => **Fri Aug 09 2024 00:00:00 GMT+0300**
console.log(d.toUTCString()) => **Thu, 08 Aug 2024 21:00:00 GMT**
console.log(d.toISOString()) => **2024-08-08T21:00:00.000Z**
```

So I'm assuming that you have GMT+8 🤷 
This issue is not related to the **datepicker**, please search in the internet
