### ISSUE TITLE
Is there a way to set the endDate time to 23:59 in range mode?

### ISSUE THREAD

**Issue by beingtyson** [rehookify/datepicker#61]
I want to fix the time of the endDate in range mode. 
However, I want the time to be set to the current time when a custom button I created is clicked. 
Only when the endDate is selected through the calendar should the time be fixed. Is there a way to achieve this?

**Comment by Feshchenko** [comment]
@beingtyson, hey, thanks for reaching out.
Currently, we can't do this with the library functionality. You can do this before sending range to the server

**Comment by Feshchenko** [comment]
@beingtyson please check this [Sandbox](https://codesandbox.io/p/sandbox/range-with-different-end-date-tqst5j)
`main.tsx` line 53
