### ISSUE TITLE
Can't see the examples on Codesandbox

### ISSUE THREAD

**Issue by CodingDive** [rehookify/datepicker#64]
![image](https://github.com/rehookify/datepicker/assets/28842311/45bac32a-3a11-4e50-9e3b-b5eac8b4815e)

**Comment by dohomi** [comment]
any news on this? I would love to see what you can build with this datepicker hook.

**Comment by Feshchenko** [comment]
Hey @dohomi @CodingDive I moved all examples from Devbox to Sandbox. 
This issue should be solved, you can check on [Examples](https://www.rehookify.com/datepicker/examples)

**Comment by dohomi** [comment]
I checked the examples page, but none of the examples opens. 
<img width="780" alt="Screenshot 2024-08-12 at 08 37 00" src="https://github.com/user-attachments/assets/6109c09d-8599-4a30-943e-52df4b632bfd">

**Comment by dohomi** [comment]
@Feshchenko could you double check the docs? I don't see any example
