### ISSUE TITLE
returned months wrong in 6.6.4 (double March for 2023)

### ISSUE THREAD

**Issue by gunters63** [rehookify/datepicker#65]
Hi,

our automated UI tests flagged an error after we updated the @rehookify/datepicker package from 6.6.1 to 6.6.4

The returned months from the hook suddenly contains March twice for 2023, here a screenshot:

![image](https://github.com/user-attachments/assets/2012df49-e035-49d4-9710-43ea565b403c)

**Comment by VaibhavGupta-creditas** [comment]
Any update regarding this error? I am also facing the same issue in version 6.6.4

**Comment by Feshchenko** [comment]
hey @gunters63 and @VaibhavGupta-creditas for reporting this issue
Please upgrade to v6.6.6 👿
