### ISSUE TITLE
is it possible to revert back node engine check from node 18 to 16 to support legacy react project ?

### ISSUE THREAD

**Issue by pramahaditamaputra** [rehookify/datepicker#68]
Link : https://github.com/rehookify/datepicker/commit/5c332162865ea8e1e2dcfe95955b2c7dbb818375#diff-9006b970ec4ded702378126a04296a77998d774e9f62013f1131a6c75434ba8c

<img width="1379" alt="Screenshot 2024-08-29 at 11 17 14" src="https://github.com/user-attachments/assets/b18d7f63-c18d-465b-8ce2-3b293012ec3c">

is it possible to revert back node engine check from node 18 to 16 to support legacy react project ?

**Comment by pramahaditamaputra** [comment]
@Feshchenko

**Comment by Feshchenko** [comment]
@pramahaditamaputra is it an issue to bump Node to 18, it would be good for your project?
16 is no longer supported by the NodeJS team https://nodejs.org/en/about/previous-releases#release-schedule

**Comment by pramahaditamaputra** [comment]
yeah it is make an issue because currently my project requirements need to use node below v18, could you revert it back to 16 please ? @Feshchenko

**Comment by Feshchenko** [comment]
@pramahaditamaputra please update to [v6.6.7](https://github.com/rehookify/datepicker/releases/tag/v6.6.7)

**Comment by pramahaditamaputra** [comment]
thank you so much @Feshchenko
