### ISSUE TITLE
"isToday" flag for month and year

### ISSUE THREAD

**Issue by tamazlykar** [rehookify/datepicker#7]
Hi. It is a proposal for the "isToday" flag for the CalendarMonth, and CalendarYear. Similar to CalendarDay.isToday.
This could be handy to have the ability to recognize the current month and year to highlight it.
I can try to implement this if it suits your vision of the project, but not sure about a good naming for this flag.

**Comment by Feshchenko** [comment]
The name for this field could be `now` :)
Then it will be good to change this field for days as well, to be consistent.
But it is a change in API so version should be v4.0.0
Probably I should create a branch for v4.0.0 and gather features like this there.

**Comment by tamazlykar** [comment]
Yes, I also can't find a good name for this property without a breaking change.
But we could be non-breaking by adding a `now` property to days and deprecating `isToday`. 
And `now` should have priority over `isToday`. What do you think?

**Comment by Feshchenko** [comment]
Yes, good strategy 👍

**Comment by Feshchenko** [comment]
Will publish this updates today near midnight.

**Comment by Feshchenko** [comment]
These changes was released 👉 https://github.com/rehookify/datepicker/releases/tag/v3.2.0
