### ISSUE TITLE
Sandbox example not found - cannot be open

### ISSUE THREAD

**Issue by pramahaditamaputra** [rehookify/datepicker#71]
https://codesandbox.io/p/sandbox/range-with-context-hooks-zlm8yr

https://codesandbox.io/p/sandbox/time-picker-with-multiple-dates-fwq2gk

above example not found - cannot be open

**Comment by Feshchenko** [comment]
Hey, @pramahaditamaputra I checked all links from the [Examples](https://www.rehookify.com/datepicker/examples) - everything working.

**Comment by tahaf22labs** [comment]
@Feshchenko , Not working for me either.
