### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by brandanking-decently** [rehookify/datepicker#74]
This app currently does not support React 19. With React 19 now entering RC-1 and seemingly more likely to be released soon and the release of NextJS 15. Do you plan of upgrading this package to support React 19 when it comes out. If so are you likely to do this before the official release of React 19 or wait. If so what will the likely wait for this be?

Looking into the project files, I believe you can achieve compatibility by upgrading the peer dependencies

**Comment by Feshchenko** [comment]
Hey, @brandanking-decently 
React v19 added to [v6.6.8](https://github.com/rehookify/datepicker/releases/tag/v6.6.8)
